### ISSUE TITLE
error while trying to split

### ISSUE THREAD

**Issue by RichardCorbett** [ExaScience/elprep#7] opened 2015-03-19 20:53 UTC
Hi.
I have a 100X human bam file (about 210G)  that I want to mark duplicates inside.

I have a server with about 800Gb of RAM, but judging by your description it would be unsafe to try marking duplicates without splitting first.

When I try the splitting command like this:
elprep-v2.10/elprep split bam.merged.bam splitFiles --output-prefix bamMerged --output-type sam

I get the following error:
"view: invalid option -- '@'
open: No such file or directory
[main_samview] fail to open file for reading.
view: invalid option -- '@'
[main_samview] fail to open file for reading.
view: invalid option -- '@'
[main_samview] fail to open file for reading.
"
I have a hunch that there is a problem with version of samtools, but its only a guess.  Do you have any ideas?

**Comment by caherzee** [comment] 2015-03-20 11:06
Hi,


On 19 Mar 2015, at 21:53, lonestar21 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi.
I have a 100X human bam file (about 210G) that I want to mark duplicates inside.

I have a server with about 800Gb of RAM, but judging by your description it would be unsafe to try marking duplicates without splitting first.

When I try the splitting command like this:
elprep-v2.10/elprep split bam.merged.bam splitFiles --output-prefix bamMerged --output-type sam

One problem I see with your invocation, is that the second argument passed to the split command should be a path.

So you would rather have to write something like:

elprep split bam.merged.bam ./splitFiles/ —output-prefix bamMarged —output-type sam

I have added a check for this in the next release of elprep for this.

However, I would not expect this to produce the error you list below. Which version of samtools are you using?

Thanks for testing.

Best,

Charlotte


I get the following error:
"view: invalid option -- '@'
open: No such file or directory
[main_samview] fail to open file for reading.
view: invalid option -- '@'
[main_samview] fail to open file for reading.
view: invalid option -- '@'
[main_samview] fail to open file for reading.
"
I have a hunch that there is a problem with version of samtools, but its only a guess. Do you have any ideas?

**Comment by lonestar21** [comment] 2015-03-20 15:34
Hi.
I created the bam I am analyzing using sambamba.   The samtools I have in my path is 0.1.16 (does it use the samtools in my path, or something built in to the code?).

Thanks for your help.   While I have your attention, maybe you could help me figure out the workflow as well.   I actually started with 5 single lane bams (created with Picard 1.71) which I merged with sambamba and then tried to markduplicates with using elprep.   Would you recommend instead doing some sort of merge/markduplicates in one command with elprep?

**Comment by lonestar21** [comment] 2015-03-20 19:59
BTW. We are hoping to make a decision on which tool to use in our pipeline early next week, so if you have any ideas for a fix I'd be excited to hear about it soon.
thanks,
RIchard

**Comment by caherzee** [comment] 2015-03-23 13:09
Hi Richard,

On 20 Mar 2015, at 16:34, lonestar21 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi.
I created the bam I am analyzing using sambamba. The samtools I have in my path is 0.1.16 (does it use the samtools in my path, or something built in to the code?).

We have only tested elPrep with version 0.1.19 and up, and would strongly recommend using version 1.2 if that is possible. elPrep indeed uses the samtools it finds in your path. If you are using our Python wrappers to use elPrep, you can edit those to change the version of samtools it uses if you cannot change the samtools version in your path itself (see elprep_io_wrapper.py).


Thanks for your help. While I have your attention, maybe you could help me figure out the workflow as well. I actually started with 5 single lane bams (created with Picard 1.71) which I merged with sambamba and then tried to markduplicates with using elprep. Would you recommend instead doing some sort of merge/markduplicates in one command with elprep?

I am not entirely sure I understand your workflow, so please correct me if I am wrong. Do I understand it correctly that you start from raw fastq files from 5 lanes that you align to get 5 bam files? Then you merge those bam files with sambamba to feed 1 big input file to elprep?

I would suggest to do this a bit different. elPrep2.2 can take multiple files as input, so there is no need to merge the input files beforehand with sambamba.

For example, after alignment, you could simple call the following command:

elprep-sfm.py ./inputs/ $output --mark-duplicates --sorting-order coordinate --nr-of-threads 12

This assumes that your input bams are all stored in the directory ./inputs/. This command uses our python wrapper (elprep-sfm.py) to call the elprep split/merge tools, see elprep-sfm.py. The command also only lists duplicate marking and sorting as processing options, so you would have to add any other filters you would like to be applied in the same command.

Does that make sense?

Best,

Charlotte

**Comment by lonestar21** [comment] 2015-03-23 15:42
Thanks Charlotte.
Yes, the workflow is that we run 5 individual Illumina lanes, which are aligned and sorted and dupMarked independently.  The pipeline sorts and dup marks all the lanes individually because often we just need one lane of data.  However, sometimes we need a really deep genome, and in those cases merge and dup mark the 5 individual sorted and dup marked bams.

I tried running your wrapper as you listed above.  I first changed all the references to samtools to use samtools 1.2 and then ran this command:
"/python-2.7.5/bin/python /home//elprep-v2.10/elprep-sfm.py /SAMBAMTools/splitFiles/ /SAMBAMTools/elOut/ --mark-duplicates --sorting-order coordinate --nr-of-threads 32"

...and got this error:
"Traceback (most recent call last):
  File "/home/rcorbett/aligners/elprep-v2.10/elprep-sfm.py", line 44, in <module>
    elprep_sfm()
  File "/home/rcorbett/aligners/elprep-v2.10/elprep-sfm.py", line 26, in elprep_sfm
    elprep_io_wrapper.cmd_wrap_input(["elprep", "split"], file_in, split_dir, ["--output-prefix", output_prefix, "--output-type", "sam"] + nr_of_threads_opt)
  File "/home/rcorbett/aligners/elprep-v2.10/elprep_io_wrapper.py", line 44, in cmd_wrap_input
    subprocess.call(cmd_list + [file_in, file_out] + cmd_opts)
  File "/gsc/software/linux-x86_64/python-2.7.5/lib/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/gsc/software/linux-x86_64/python-2.7.5/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/gsc/software/linux-x86_64/python-2.7.5/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
"
I printed the values of the variables before line 43 of iowrapper  here:
"['elprep', 'split'] /SAMBAMTools/splitFiles/ /SAMBAMTools/temp-1427124912.48/ ['--output-prefix', '', '--output-type', 'sam', '--nr-of-threads', '32']"

**Comment by caherzee** [comment] 2015-03-23 16:10
Hi Richard,

The problem I see is that the elprep command expects the 2nd argument to be the name of an output file, while you provided a path. Try changing /SAMBAMTools/elOut/ to /SAMBAMTools/elOut/output.bam

Does that work?

Best,

Charlotte

On 23 Mar 2015, at 16:42, lonestar21 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Charlotte.
Yes, the workflow is that we run 5 individual Illumina lanes, which are aligned and sorted and dupMarked independently. The pipeline sorts and dup marks all the lanes individually because often we just need one lane of data. However, sometimes we need a really deep genome, and in those cases merge and dup mark the 5 individual sorted and dup marked bams.

I tried running your wrapper as you listed above. I first changed all the references to samtools to use samtools 1.2 and then ran this command:
"/python-2.7.5/bin/python /home//elprep-v2.10/elprep-sfm.py /SAMBAMTools/splitFiles/ /SAMBAMTools/elOut/ --mark-duplicates --sorting-order coordinate --nr-of-threads 32"

...and got this error:
"Traceback (most recent call last):
File "/home/rcorbett/aligners/elprep-v2.10/elprep-sfm.py", line 44, in
elprep_sfm()
File "/home/rcorbett/aligners/elprep-v2.10/elprep-sfm.py", line 26, in elprep_sfm
elprep_io_wrapper.cmd_wrap_input(["elprep", "split"], file_in, split_dir, ["--output-prefix", output_prefix, "--output-type", "sam"] + nr_of_threads_opt)
File "/home/rcorbett/aligners/elprep-v2.10/elprep_io_wrapper.py", line 44, in cmd_wrap_input
subprocess.call(cmd_list + [file_in, file_out] + cmd_opts)
File "/gsc/software/linux-x86_64/python-2.7.5/lib/python2.7/subprocess.py", line 524, in call
return Popen(popenargs, *kwargs).wait()
File "/gsc/software/linux-x86_64/python-2.7.5/lib/python2.7/subprocess.py", line 711, in init
errread, errwrite)
File "/gsc/software/linux-x86_64/python-2.7.5/lib/python2.7/subprocess.py", line 1308, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
"
I printed the values of the variables before line 43 of iowrapper here:
"['elprep', 'split'] /SAMBAMTools/splitFiles/ /SAMBAMTools/temp-1427124912.48/ ['--output-prefix', '', '--output-type', 'sam', '--nr-of-threads', '32']"

—
Reply to this email directly or view it on GitHub<https://github.com/ExaScience/elprep/issues/7#issuecomment-85054830>.

---
Charlotte Herzeel, PhD
Researcher at ExaScience Life Lab (via IMEC)
Address: Kapeldreef 75, 3001 Leuven, Belgium
Phone: +32 16 28 83 06

**Comment by lonestar21** [comment] 2015-03-23 16:17
Hi Charlotte. Thanks for the quick reply!
For some reason, I don't see any difference from the output above.  I've changed the output path to be a .bam file, but I still get the same error.  Any other ideas?

**Comment by caherzee** [comment] 2015-03-23 16:30
Hi,

Do you mind posting the error message anyway? I want to make sure we are not missing something here. Just to be sure, the path /SAMBAMTools/splitFiles/ is where the 5 unprocessed input bams are stored?

Charlotte
On 23 Mar 2015, at 17:17, lonestar21 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Charlotte. Thanks for the quick reply!
For some reason, I don't see any difference from the output above. I've changed the output path to be a .bam file, but I still get the same error. Any other ideas?

**Comment by lonestar21** [comment] 2015-03-23 16:32
Hi Charlotte, Yes, the splitFiles folder is where the individual bams are stored.   I'm looking through the python code now to see if I can figure it out, but I'm not much of a python guy, so this could be tricky.  Thanks so much for your help.


/gsc/software/linux-x86_64/python-2.7.5/bin/python /home/rcorbett/aligners/elprep-v2.10/elprep-sfm.py /projects/rcorbettprj2/SAMBAMTools/splitFiles/ /projects/rcorbettprj2/SAMBAMTools/elOut.bam --mark-duplicates --sorting-order coordinate --nr-of-threads 32
['elprep', 'split'] /projects/rcorbettprj2/SAMBAMTools/splitFiles/ /projects/rcorbettprj2/SAMBAMTools/splitFiles/temp-1427128264.28/ ['--output-prefix', '', '--output-type', 'sam', '--nr-of-threads', '32']
Traceback (most recent call last):
  File "/home/rcorbett/aligners/elprep-v2.10/elprep-sfm.py", line 44, in <module>
    elprep_sfm()
  File "/home/rcorbett/aligners/elprep-v2.10/elprep-sfm.py", line 26, in elprep_sfm
    elprep_io_wrapper.cmd_wrap_input(["elprep", "split"], file_in, split_dir, ["--output-prefix", output_prefix, "--output-type", "sam"] + nr_of_threads_opt)
  File "/home/rcorbett/aligners/elprep-v2.10/elprep_io_wrapper.py", line 44, in cmd_wrap_input
    subprocess.call(cmd_list + [file_in, file_out] + cmd_opts)
  File "/gsc/software/linux-x86_64/python-2.7.5/lib/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/gsc/software/linux-x86_64/python-2.7.5/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/gsc/software/linux-x86_64/python-2.7.5/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by lonestar21** [comment] 2015-03-23 16:34
It  looks like the elprep-sfm.py script is built for handling single files.   There is some parsing to pull out basenames and extrensions that only seem to do something when the input is a single file.   Maybe you have a different version?

**Comment by caherzee** [comment] 2015-03-23 16:35
Hi Richard,

I only saw just now in your trace that you are still using elprep-v2.10. Can you try with elprep-v2.2? That is the latest version of elprep. The multiple input files did not work in elprep-v2.10.

Cheers,

Charlotte


On 23 Mar 2015, at 17:29, Charlotte Herzeel (imec) <Charlotte.Herzeel@imec.be<mailto:Charlotte.Herzeel@imec.be>> wrote:

Hi,

Do you mind posting the error message anyway? I want to make sure we are not missing something here. Just to be sure, the path /SAMBAMTools/splitFiles/ is where the 5 unprocessed input bams are stored?

Charlotte
On 23 Mar 2015, at 17:17, lonestar21 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Charlotte. Thanks for the quick reply!
For some reason, I don't see any difference from the output above. I've changed the output path to be a .bam file, but I still get the same error. Any other ideas?

**Comment by lonestar21** [comment] 2015-03-23 16:35
Ah.  Let me give it a shot and get back to you.

**Comment by lonestar21** [comment] 2015-03-23 16:40
Hmmm. Same error.  I've pasted the entire command without pulling out the full paths.  Hopefully its still readable.

"/gsc/software/linux-x86_64/python-2.7.5/bin/python /home/rcorbett/aligners/elprep-v2.2/elprep-sfm.py /projects/rcorbettprj2/SAMBAMTools/splitFiles/ /projects/rcorbettprj2/SAMBAMTools/elOut.bam --mark-duplicates --sorting-order coordinate --nr-of-threads 32
Traceback (most recent call last):
  File "/home/rcorbett/aligners/elprep-v2.2/elprep-sfm.py", line 55, in <module>
    elprep_sfm()
  File "/home/rcorbett/aligners/elprep-v2.2/elprep-sfm.py", line 26, in elprep_sfm
    elprep_io_wrapper.cmd_wrap_input(["elprep", "split"], file_in, split_dir, ["--output-prefix", output_prefix, "--output-type", "sam"] + nr_of_threads_opt)
  File "/home/rcorbett/aligners/elprep-v2.2/elprep_io_wrapper.py", line 43, in cmd_wrap_input
    subprocess.call(cmd_list + [file_in, file_out] + cmd_opts)
  File "/gsc/software/linux-x86_64/python-2.7.5/lib/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/gsc/software/linux-x86_64/python-2.7.5/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/gsc/software/linux-x86_64/python-2.7.5/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
"

**Comment by lonestar21** [comment] 2015-03-23 17:30
The 2.2 download I just pulled, still seems to not really be understanding that the input is a few bams in a folder.

**Comment by lonestar21** [comment] 2015-03-23 17:33
Maybe this is related... I tried running a single bam command without the wrapper to see what happens.  
"/home/rcorbett/aligners/elprep-v2.2/elprep split /projects/rcorbettprj2/SAMBAMTools/splitFiles/P00276_C4PGPANXX_3.bam /projects/rcorbettprj2/SAMBAMTools/elOut/"

This gave an error in the log file:
"An error occurred in elPrep 2.2: Unknown tag GO in SAM header line #S(ELPREP::SCANNER :INDEX 14 :STRING "@HD    VN:1.0  GO:none SO:coordinate")."

**Comment by keithj** [comment] 2015-03-23 17:59
The "-@" command line option to samtools appeared first in samtools 0.1.19. My guess is you are using 0.1.18 or earlier.

**Comment by lonestar21** [comment] 2015-03-23 18:03
I'm using 0.1.19 and 1.2 with the same results. The error above seems like a complaint about the GO term in the header of our bams, which is in the samtools spec, though it only appears in some versions.

**Comment by lonestar21** [comment] 2015-03-23 18:05
If I reheader a single bam to take out the "GO" term, it appears I can run "elprep split".  It hasn't finished yet, but its the first time I don't get an immediate error.

**Comment by keithj** [comment] 2015-03-23 18:06
I see. Sorry, I did not read closely enough to see that there are multiple issues here.

**Comment by keithj** [comment] 2015-03-23 18:15
A tag of GO:none in the HD header is valid according to the current SAM spec. If elprep rejects it then I think that is a bug.

**Comment by pcostanza** [comment] 2015-03-23 19:41
Keith, thanks a lot for helping with finding the problem. The problem is that elPrep 2.20 is still based on the SAM file specification version 1.4. We still have to update elPrep to reflect the changes in the SAM file specification version 1.5. We will do this as soon as possible.

**Comment by caherzee** [comment] 2015-03-25 13:26
Hi Richard,

Were you able to make progress this way?

Best,

Charlotte

On 23 Mar 2015, at 19:05, lonestar21 <notifications@github.com<mailto:notifications@github.com>> wrote:


If I reheader a single bam to take out the "GO" term, it appears I can run "elprep split". It hasn't finished yet, but its the first time I don't get an immediate error.

**Comment by lonestar21** [comment] 2015-03-25 15:35
Hi Charlotte,
I was able to run this command successfully:
"python /home/rcorbett/aligners/elprep-v2.2/elprep-sfm.py /projects/rcorbettprj2/SAMBAMTools/reheader/P00276_C4PGPANXX_3.noGO.bam /projects/rcorbettprj2/SAMBAMTools/reheader/elOut.bam --mark-duplicates --sorting-order coordinate --nr-of-threads 32"

As mentioned above, I had to reheader the initial bam to take out the "GO:none" term.   
The other moment of truth came when I read through and tried to run some of your example scripts.   Only at that time did I realize that you need both the path to elprep, and your SAMtools binary in your path at execution time.

I never did get an example working that merged and dup marked my 5 individual bams.   That may be something we could figure out using your wrappers as an example, but I didn't find a way to do it using the wrappers supplied with 2.20.   I'm probably missing something though.

**Comment by pcostanza** [comment] 2015-03-27 08:33
With regard to the GO tag: This should be resolved with the newest elPrep 2.30 release. We have also checked for other changes in the SAM file specification (version 1.5 as of 3 Mar 2015), and we believe everything should be fine. There was also an issue with sorting order coordinate for unmapped reads, which we also fixed.

How relevant is the GO tag? elPrep so far supports sorting according to coordinate order and queryname order. Would a command that groups according to GO=query or GO=reference, without doing a full sort, be interesting?

Pascal

**Comment by keithj** [comment] 2015-03-27 08:47
Regarding the GO tag, I recall implementing in in cl-sam, back in about 2009, at a time when the SAM spec. was mutating regularly. At some point after that it was removed. It has now been restored, but I do not know the use case that influenced that decision. If I find out, I will let you know.

**Comment by caherzee** [comment] 2015-03-27 12:35
Hi Richard,

On 25 Mar 2015, at 16:35, lonestar21 <notifications@github.com<mailto:notifications@github.com>> wrote:

I never did get an example working that merged and dup marked my 5 individual bams. That may be something we could figure out using your wrappers as an example, but I didn't find a way to do it using the wrappers supplied with 2.20. I'm probably missing something though.

—
Reply to this email directly or view it on GitHub<https://github.com/ExaScience/elprep/issues/7#issuecomment-86084726>.

It is a bit hard for me to understand what is going wrong here. I have ran the following call without problems on multiple input files which are all stored in a directory “./inputs/":

elprep-sfm.py ./inputs/ output.bam --mark-duplicates --sorting-order coordinate --nr-of-threads 24

Did you get any error message when trying to execute your elprep call? elPrep should normally create a log file when an error occurs. It should by default be created in your home directory: /home/your_user_name/logs/elprep/. Do you see any log there?

Thanks again for testing.

Best,

Charlotte

**Comment by lonestar21** [comment] 2015-04-08 23:12
Hi Charlotte,
I'm using 2.3 now and although things are still running, it looks like we've gotten off the ground for the merge/markduplicates command.   Hopefully I'll have results in a few hours.

**Comment by lonestar21** [comment] 2015-04-09 15:50
Hi again.  The run finished successfully overnight.  Here is a summary of my results/experience...
I merged/dupmarked 5 large bams, which resulted in about a 100X bam after merging.

I ran the command just as you suggested:
elprep-sfm.py ./inputs/ output.bam --mark-duplicates --sorting-order coordinate --nr-of-threads 24

-The merge/markduplicates took just about 16 hours when I gave it 32 threads to use.  The split command took about 4 hours to finish, then the separate chromosome .sam files were processed with elprep, the largest of which was chromosome 1, using about 515 gigs of RAM at its peak and taking about 40 minutes. In total, the processing of all the chomosomes took about 7 hours.   Finally, the merge step took about 5 hours, resulting in a very large SAM file.

I was a little surprised to see that the output came in .sam format (not bam).

For comparison, I've done the same merge/markdups using sambamba and novosort in about 5 hours.  Does it look like I'm doing something that would make it slower than it needs to be?

**Comment by caherzee** [comment] 2015-04-13 09:01
Hi Richard,

On 09 Apr 2015, at 17:50, lonestar21 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi again. The run finished successfully overnight. Here is a summary of my results/experience...
I merged/dupmarked 5 large bams, which resulted in about a 100X bam after merging.

I ran the command just as you suggested:
elprep-sfm.py ./inputs/ output.bam --mark-duplicates --sorting-order coordinate --nr-of-threads 24

-The merge/markduplicates took just about 16 hours when I gave it 32 threads to use. The split command took about 4 hours to finish, then the separate chromosome .sam files were processed with elprep, the largest of which was chromosome 1, using about 515 gigs of RAM at its peak and taking about 40 minutes. In total, the processing of all the chomosomes took about 7 hours. Finally, the merge step took about 5 hours, resulting in a very large SAM file.

I was a little surprised to see that the output came in .sam format (not bam).

For comparison, I've done the same merge/markdups using sambamba and novosort in about 5 hours. Does it look like I'm doing something that would make it slower than it needs to be?

I don’t have the impression you did anything wrong here.

There are a number of tools that optimise certain steps (mostly sorting and duplicate marking) that are faster than elPrep when comparing those individual steps. The main advantage of elPrep, however, is that it optimises the execution of *many* filtering steps. If you would add more filters to the elPrep command, for example for filtering out unmapped reads, filtering out corrupted data, filtering the sequence dictionary, replacing read groups, etc, you would see that the runtime with elPrep remains stable.

However, since your pipeline has only two steps, you may not see the advantage of using elPrep when comparing to tools optimised for these specific steps. If you only want to do sorting and duplicate marking, you are currently indeed better of with using faster tools such as novosort that optimise those steps.

With regard to the output ending up in .sam format, I am not sure what is going on. That shouldn’t happen when specifying the extension of the output file as .bam. I cannot reproduce this problem.

Thanks again for testing and sharing your results, we really appreciate that.

Best,

Charlotte

**Closed** 2016-11-07 12:29 UTC
